apiVersion: v1alpha1
kind: User
metadata:
  name: anonymousUser
  labels:
    halo.run/hidden-user: "true"
  finalizers:
    - system-protection
spec:
  displayName: Anonymous User
  email: anonymous@example.com
  disabled: true

---
apiVersion: v1alpha1
kind: User
metadata:
  name: ghost
  labels:
    halo.run/hidden-user: "true"
  finalizers:
    - system-protection
spec:
  displayName: LoarAlt
  email: ghost@example.com
  disabled: true
  bio: 一蓑烟雨任平生

